# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Word(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, imageurl: str=None):  # noqa: E501
        """Word - a model defined in Swagger

        :param id: The id of this Word.  # noqa: E501
        :type id: str
        :param name: The name of this Word.  # noqa: E501
        :type name: str
        :param imageurl: The imageurl of this Word.  # noqa: E501
        :type imageurl: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'imageurl': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'imageurl': 'imageurl'
        }
        self._id = id
        self._name = name
        self._imageurl = imageurl

    @classmethod
    def from_dict(cls, dikt) -> 'Word':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Word of this Word.  # noqa: E501
        :rtype: Word
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Word.


        :return: The id of this Word.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Word.


        :param id: The id of this Word.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Word.


        :return: The name of this Word.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Word.


        :param name: The name of this Word.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def imageurl(self) -> str:
        """Gets the imageurl of this Word.


        :return: The imageurl of this Word.
        :rtype: str
        """
        return self._imageurl

    @imageurl.setter
    def imageurl(self, imageurl: str):
        """Sets the imageurl of this Word.


        :param imageurl: The imageurl of this Word.
        :type imageurl: str
        """
        if imageurl is None:
            raise ValueError("Invalid value for `imageurl`, must not be `None`")  # noqa: E501

        self._imageurl = imageurl
